import React from "react";
import "../css/Projects.css";

export const Projects = () => {
  const projects = [
    {
      title: "Meals & Recipes (iOS)",
      desc: "Simple iOS app for meal preparation to help plan dinner for my family. Built with SwiftUI",
      link: "https://github.com/escosio/MealsAndRecipes",
    },
    {
      title: "Alejo Minis",
      desc: "React site for a friend mini painter who does commissions and has a working contact form through EmailJS.",
      link: "https://alejo-minis.vercel.app/",
    },
    {
      title: "Meals & Recipes (Web)",
      desc: "Same as the iOS app but in React.js so I don't have to get an Apple Developer license. Mostly using React Bootstrap.",
      link: "https://meals-and-recipes-web.vercel.app/"
    },
    {
      title: "Espresso practice",
      desc: "Learning Espresso at Peloton through a mentorship program. This is where I was introduced to Kotlin & then Espresso before becoming a contributor to the actual test repo.",
      link: "https://github.com/pl-peloton/scott-pai-emp",
    },
    {
      title: "Narwhals & Sea Turtles",
      desc: "Using AWS to host a static website in S3 for my daughter. The HTML &  styling was generated by ChatGPT, the purpose was to practice using AWS.",
      link: "https://smd-bucket-1690639694.s3.amazonaws.com/index.html"
    }
  ];

  return (
    <div id="projects" className="section project-card-container">
      <h2>Projects <i class="fa-solid fa-code-branch"></i></h2>
      <p>Here are some things I have been working on:</p>
      {projects.map((project, i) => (
          <a href={project.link} key={i} target="_blank">
        <div key={i} className="project-card">
            <h3>{project.title}</h3>
          <p>{project.desc}</p>
        </div>
        </a>
      ))}
    </div>
  );
};
